polish module test github action

diff --git a/.github/workflows/test-kernel-module.yaml b/.github/workflows/test-kernel-module.yaml
--- a/.github/workflows/test-kernel-module.yaml
+++ b/.github/workflows/test-kernel-module.yaml
@@ -5,11 +5,13 @@ on:
       instance-type:
         description: 'EC2 instance type to use'
         required: false
-        default: 'c7i.metal-24xl'
+        default: 'm7i.metal-24xl'
         type: string
   push:
     branches:
       - main
+    paths:
+      - module/**
 
 permissions:
   id-token: write # Required for requesting the JWT
@@ -146,11 +148,6 @@ jobs:
           # we do not unmount, maybe mounting affects the intel_cqm checks below
           #sudo umount /sys/fs/resctrl || true           
       
-      - name: Run the interval dmesg reader
-        working-directory: module
-        run: |
-          ./run_module.sh
-
       - name: Load and test module
         id: load-and-test-module
         continue-on-error: true
@@ -162,25 +159,39 @@ jobs:
           sudo objdump -d build/collector.ko | grep undefined || true
 
           # Load module
+          echo "insmod build/collector.ko:"
           sudo insmod build/collector.ko
           
           # Verify module is loaded
+          echo "lsmod | grep collector:"
           lsmod | grep collector
           
           # Check kernel logs for module initialization
-          dmesg | grep "Memory Collector" || true
+          echo "dmesg | grep 'Memory Collector':"
+          dmesg -c | grep "Memory Collector" || true
           
           # Unload module
+          echo "rmmod collector:"
           sudo rmmod collector
           
           # Verify module unloaded successfully
+          echo "lsmod | grep collector:"
+          lsmod | grep collector
           if lsmod | grep -q collector; then
             echo "Error: Module still loaded"
             exit 1
           fi
           
           # Check kernel logs for cleanup message
-          dmesg | grep "Memory Collector" || true
+          echo "dmesg | grep 'Memory Collector':"
+          dmesg -c | grep "Memory Collector" || true
+
+      - name: Check dmesg on failure
+        if: steps.load-and-test-module.outcome == 'failure'
+        run: |
+          echo "load and test module failed, showing last kernel messages:"
+          sudo dmesg | tail -n 100
+          exit 1
 
       - name: Install trace dependencies
         run: |
@@ -189,15 +200,12 @@ jobs:
       - name: Run module test script
         working-directory: module
         run: |
+          # run 10 times in quick succession to stress-test insmod/rmmod and collector
+          for i in {1..10}; do
+            echo "*** Run $i:"
+            ./test_module.sh
+          done
 
-          ./test_module.sh
-
-      - name: Check dmesg on failure
-        if: steps.load-and-test-module.outcome == 'failure'
-        run: |
-          echo "load and test module failed, showing last kernel messages:"
-          sudo dmesg | tail -n 100
-          exit 1
 
   stop-runner:
     name: Stop EC2 runner
